

file:
  path: ./docs/microblogging.xlsx
  columnName: Text


clean_data: 1

analyzing_model: CAMeL-Lab/bert-base-arabic-camelbert-da-sentiment # Arabic
# analyzing_model: cardiffnlp/twitter-roberta-base-sentiment # English
# analyzing_model: cardiffnlp/twitter-xlm-roberta-base-sentiment # MultiLang




